// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnwiwqvjskbojariowax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impud2l3cXZqc2tib2phcmlvd2F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTg0NjksImV4cCI6MjA2Nzg3NDQ2OX0.Q8l09tkMpJg2pIHyh78Ji8Ime8atrZ3tWPOFQdUad-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});